Update list.md
ZcashFoundation/zfnd pull request #120
Opened 2020-12-07 20:12 UTC by einotna

2020-12-07 20:28 UTC, mpguerra requested changes
One small fix

2020-12-07 20:28 UTC, mpguerra commented on about/incorporation-docs/list.md
> +- [Bylaws Amendment 2](https://www.zfnd.org/about/incorporation-docs/2020-12-01-bylaws-amendment-3/)
```suggestion
- [Bylaws Amendment 3](https://www.zfnd.org/about/incorporation-docs/2020-12-01-bylaws-amendment-3/)
```

2020-12-08 00:21 UTC, einotna commented on about/incorporation-docs/list.md
> +- [Bylaws Amendment 2](https://www.zfnd.org/about/incorporation-docs/2020-12-01-bylaws-amendment-3/)
I think I changed it?

2020-12-08 11:29 UTC, mpguerra approved these changes

2020-12-08 11:37 UTC, merged